services:
  server:
    build: ./server
    ports:
      - '8080:8080'
    volumes:
      - ./server/pb_data:/pb/pb_data
      - ./server/pb_migrations:/pb/pb_migrations
      - ./server/pb_hooks:/pb/pb_hooks
